test:
	cargo test syncs_vara_solochain
	cargo test syncs_shibuya_solochain

	cargo test syncs_kusama_relay_chain
	cargo test syncs_polkadot_relay_chain
	cargo test syncs_westend_relay_chain
	cargo test syncs_rococo_relay_chain

	# cargo test syncs_kusama_statemine_parachain
	cargo test syncs_kusama_asset_hub_parachain
	cargo test syncs_kusama_bridge_hub_parachain
	cargo test syncs_kusama_shiden_parachain
	cargo test syncs_kusama_karura_parachain

	# cargo test syncs_polkadot_statemint_parachain
	cargo test syncs_polkadot_asset_hub_parachain
	cargo test syncs_polkadot_bridge_hub_parachain
	cargo test syncs_polkadot_astar_parachain

	cargo test syncs_westend_asset_hub_parachain
	cargo test syncs_westend_bridge_hub_parachain

	cargo test syncs_rococo_asset_hub_parachain
	cargo test syncs_rococo_bridge_hub_parachain
